server:
  port: 8005
spring:
  application:
    name: feign-consumer
  cloud:
    zookeeper:
      enabled: true
      discovery:
        preferIpAddress: true
        register: true
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 6000
      removal-provider:
        connectTimeout: 1000
        readTimeout: 1000
      removalBootService:
        connectTimeout: 1000
        readTimeout: 1000

management:
  endpoint:
    health:
      probes:
        enabled: true
