# 离群实例摘除插件配置
removal.config:
  expireTimes: 60000  # 实例调用信息过期时间。单位：毫秒
  exceptions:         # 任务服务调用失败的异常情况
    - com.alibaba.dubbo.remoting.TimeoutException
    - org.apache.dubbo.remoting.TimeoutException
    - java.util.concurrent.TimeoutException
    - java.net.SocketTimeoutException
  enableRemoval: false  # 离群实例摘除开关
  recoveryTimes: 30000  # 实例摘除之后的恢复时间
  windowsTimes: 1000    # 离群实例异常统计窗口大小。单位：毫秒
  windowsNum: 10        # 离群实例异常统计窗口个数
  rules:                # 离群实例摘除规则，scaleUpLimit：离群实例摘除上限比例。minInstanceNum：最小实例数。
    - { scaleUpLimit: 0.6, minInstanceNum: 1, errorRate: 0.6 }