server:
  port: 28021
dubbo:
  application:
    name: dubbo-integration-provider
  protocol:
    port: ${DUBBO_PROTOCOL_PORT:28821}
    name: dubbo
  registry:
    # 模拟存量dubbo应用注册到zookeeper的情况，新开发的应用建议配置为 sc://127.0.0.1:30100
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper


spring:
  application:
    name: dubbo-integration-provider

feign:
  hystrix:
    enabled: true