register.service:
  registerType: SERVICE_COMB # 注册服务类型，支持SERVICE_COMB/NACOS
servicecomb.service:
  address: http://localhost:30100 # 注册中心地址
  heartbeatInterval: 15 # 服务实例心跳发送间隔（单位：秒）
  openMigration: false # 是否开启迁移功能
  enableSpringRegister: false # 是否开启spring插件注册能力
  enableDubboRegister: false #是 否开启dubbo插件注册能力
  sslEnabled: false # 是否开启ssl
  preferIpAddress: false # 若为true, 则采用IP地址访问代替域名方法
grace.rule:
  enableSpring: false # springCloud优雅上下线开关
  startDelayTime: 0  # 优雅上下线启动延迟时间, 单位S
  enableWarmUp: false # 是否开启预热
  warmUpTime: 120    # 预热时间, 单位S
  enableGraceShutdown: false # 是否开启优雅下线
  shutdownWaitTime: 30  # 关闭前相关流量检测的最大等待时间, 单位S. 需开启enabledGraceShutdown才会生效
  enableOfflineNotify: false # 是否开启下线主动通知
  httpServerPort: 16688 # 开启下线主动通知时的httpServer端口
  upstreamAddressMaxSize: 500 # 缓存上游地址的默认大小
  upstreamAddressExpiredTime: 60 # 缓存上游地址的过期时间
nacos.service:
  address: 127.0.0.1:8848 # nacos注册中心地址和端口号
  username: "" # nacos验证账户
  password: "" # nacos的验证密码
  namespace: "" # 命名空间，nacos配置创建命名空间的id值
  weight: 1 # 服务实例权重值
  clusterName: DEFAULT # 集群名称
  ephemeral: true # 是否是临时节点，true为是，false为否
