# 默认编译场景使用，不含示例工程
plugins:
  - flowcontrol
  - service-router
  - server-monitor
  - threadlocal
  - service-registry
  - loadbalancer
  - dynamic-config
  - monitor
  - deny-consume
adaptors:
  - lubanops
profiles:
  cse:
    - flowcontrol
    - service-router
    - service-registry
    - dynamic-config
  apm:
    - flowcontrol
    - service-router
profile: cse,apm