server:
  port: 8005
down:
  serviceName: feign-provider
spring:
  application:
    name: feign-consumer
  cloud:
    zookeeper:
      enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 6000
      removal-provider:
        connect-timeout: 1000
        read-timeout: 1000
      removalBootService:
        connect-timeout: 1000
        read-timeout: 1000

management:
  endpoint:
    health:
      probes:
        enabled: true
