spring:
  application:
    name: sermant-injector

server:
  port: 8443
  ssl:
    enabled: true
    # ssl certificate
    certificate: /home/config/sermant-injector.pem
    # private key of ssl certificate
    certificate-private-key: /home/config/sermant-injector.key
    key-store-password: default
    key-alias: sermant-injector

sermant-agent:
  image:
    # agent image address
    addr: io.sermant/sermant-agent:0.0.1
    # pulling policy of agent image
    pullPolicy: IfNotPresent
  mount:
    # disk that agent mounts
    path: /home/sermant-agent
  config:
    # Configuration center type of Sermant: ZOOKEEPER/KIE/NACOS
    type: ZOOKEEPER
    # Configuration center address of Sermant
    address: http://localhost:2181
  service:
    # Registration center type of Sermant: SERVICE_COMB/NACOS
    type: SERVICE_COMB
    # Registration center address
    address: http://localhost:30100
  # The name of the configMap that configures the environment variable in sermant-agent
  configMap: sermant-agent-env
  inject:
    # When the host application already has JAVA_TOOL_OPTIONS variables, injector injection behavior: before indicates
    # injection before the original variable (default), after indicates injection after the original variable, and
    # ignore indicates that injection is not performed
    action: before

management:
  endpoint:
    health:
      probes:
        enabled: true