server:
  port: 8005
down:
  serviceName: rest-provider
spring:
  application:
    name: rest-consumer
  cloud:
    zookeeper:
      enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
timeout: 1000