name: Dubbo Integration Test
env:
  sermantVersion: 1.0.0
on:
  push:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'sermant-agentcore/**'
      - 'sermant-plugins/sermant-dynamic-config/**'
      - 'sermant-plugins/sermant-flowcontrol/**'
      - 'sermant-plugins/sermant-loadbalancer/**'
      - 'sermant-plugins/sermant-router/**'
      - 'sermant-plugins/sermant-service-registry/**'
      - 'sermant-plugins/sermant-springboot-registry/**'
      - '.github/workflows/dubbo_integration*.yaml'
      - '.github/actions/**'
concurrency:
  group: Dubbo Integration Test-${{ github.head_ref }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  download-midwares-and-cache:
    name: download and cache middlewares
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache middlewares
        uses: actions/cache@v3
        with:
          path: |
            apache-servicecomb-service-center-*/
            apache-zookeeper-*/
            Local-CSE-2.1.3-linux-amd64.zip
          key: ${{ runner.os }}-middlewares-${{ github.run_id }}
      - name: download middlewares
        run: |
          export ROOT_PATH=$(pwd)
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh sc
          tar -zxf apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh zk
          tar -zxf apache-zookeeper-3.6.3-bin.tar.gz
          bash ./sermant-integration-tests/scripts/tryDownloadMidware.sh
  build-agent-and-cache:
    name: package and cache agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: cache agent
        uses: actions/cache@v3
        with:
          path: sermant-agent-*/
          key: ${{ runner.os }}-agent-${{ github.run_id }}
      - name: package agent
        run: |
          sed -i '/sermant-backend/d' pom.xml
          sed -i '/sermant-backend-lite/d' pom.xml
          sed -i '/sermant-integration-tests/d' pom.xml
          sed -i '/sermant-injector/d' pom.xml
          mvn package -DskipTests -Ptest --file pom.xml
  test-for-dubbo:
    name: Test for dubbo router
    runs-on: ubuntu-latest
    needs: [ download-midwares-and-cache, build-agent-and-cache ]
    strategy:
      matrix:
        dubbo-version: [ '2-6','2-7' ]
        dubbo-versions: [ '0','5','6','7','8','9','10','11','12' ]
        include:
          - dubbo-version: '2-6'
            dubbo-versions: '1'
          - dubbo-version: '2-6'
            dubbo-versions: '2'
          - dubbo-version: '2-6'
            dubbo-versions: '3'
          - dubbo-version: '2-6'
            dubbo-versions: '4'
          - dubbo-version: '2-6'
            dubbo-versions: '10.1'
          - dubbo-version: '2-7'
            dubbo-versions: '4.1'
          - dubbo-version: '2-7'
            dubbo-versions: '13'
          - dubbo-version: '2-7'
            dubbo-versions: '14'
          - dubbo-version: '2-7'
            dubbo-versions: '15'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: dubbo test common
        uses: ./.github/actions/common/dubbo
      - name: dubbo router test for ${{ matrix.dubbo-version }}
        uses: ./.github/actions/scenarios/dubbo/router
      - name: dubbo common test for ${{ matrix.dubbo-version }}
        uses: ./.github/actions/scenarios/dubbo/dubbo-common
