name: Integration Test

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-for-dubbo:
    name: Test for dubbo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dubbo-version: ['2-6','2-7']
        dubbo-versions: ['0','1','3','5','6','7','8','9','10','11','12']
        include:
          - dubbo-version: '2-6'
            dubbo-versions: '2'
          - dubbo-version: '2-6'
            dubbo-versions: '4'
          - dubbo-version: '2-6'
            dubbo-versions: '10.1'
          - dubbo-version: '2-7'
            dubbo-versions: '4.1'
          - dubbo-version: '2-7'
            dubbo-versions: '13'
          - dubbo-version: '2-7'
            dubbo-versions: '14'
          - dubbo-version: '2-7'
            dubbo-versions: '15'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: download sc
        run: |
          curl -o apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz -L https://github.com/apache/servicecomb-service-center/releases/download/v2.1.0/apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz
          tar -zxf apache-servicecomb-service-center-2.1.0-linux-amd64.tar.gz
          sh apache-servicecomb-service-center-2.1.0-linux-amd64/start-service-center.sh
      - name: download zookeeper
        run: |
          curl -o apache-zookeeper-3.8.0-bin.tar.gz -L https://dlcdn.apache.org/zookeeper/zookeeper-3.8.0/apache-zookeeper-3.8.0-bin.tar.gz
          tar -zxf apache-zookeeper-3.8.0-bin.tar.gz
          bash apache-zookeeper-3.8.0-bin/bin/zkServer.sh start apache-zookeeper-3.8.0-bin/conf/zoo_sample.cfg
      - name: package agent
        run: sed -i '/sermant-backend/d' pom.xml & mvn package -DskipTests -Pagent --file pom.xml
      - name: package dubbo 2.6.0 tests
        if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions == '0'
        run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests -P260 --file sermant-integration-tests/dubbo-test/pom.xml
      - name: package dubbo 2.6.x tests
        if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions != '0'
        run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
      - name: package dubbo 2.7.x tests
        if: matrix.dubbo-version == '2-7'
        run: mvn package -Ddubbo.version=2.7.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
      - name: start spring and dubbo provider service
        env:
          servicecomb.service.enableDubboRegister: true
          servicecomb.service.enableSpringRegister: true
          servicecomb.service.openMigration: false
          SERVICE_META_ENVIRONMENT: testing
          SERVER_PORT: 38020
          DUBBO_PROTOCOL_PORT: 38820
        run: |
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=dubbo-integration-provider -jar \
          sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-provider/target/dubbo-integration-provider.jar > spring-and-dubbo-provider.log 2>&1 &
      - name: start second spring and dubbo provider service
        env:
          servicecomb.service.enableDubboRegister: true
          servicecomb.service.enableSpringRegister: true
          servicecomb.service.openMigration: false
          SERVICE_META_ENVIRONMENT: testing
          SERVER_PORT: 38021
          DUBBO_PROTOCOL_PORT: 38821
        run: |
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=dubbo-integration-provider -jar \
          sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-provider/target/dubbo-integration-provider.jar > spring-and-dubbo-provider2.log 2>&1 &
      - name: start provider service
        env:
          servicecomb.service.enableDubboRegister: true
          servicecomb.service.openMigration: false
        run: |
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=dubbo-integration-provider -jar \
          sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-provider/target/dubbo-integration-provider.jar > dubbo-provider.log 2>&1 &
      - name: start zookeeper provider service
        env:
          SERVER_PORT: 48021
          DUBBO_PROTOCOL_PORT: 48821
        run: |
          nohup java -jar sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-provider/target/dubbo-integration-provider.jar > dubbo-zk-provider.log 2>&1 &
      - name: waiting for providers start
        run: |
          ps -ef | grep java
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:48021/ping 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28021/ping 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:38021/ping 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:38020/ping 120
          ps -ef | grep java
      - name: start spring and dubbo consumer service
        env:
          servicecomb.service.enableDubboRegister: true
          servicecomb.service.enableSpringRegister: true
          servicecomb.service.openMigration: false
          SERVICE_META_ENVIRONMENT: testing
          SERVER_PORT: 38022
          DUBBO_PROTOCOL_PORT: 38822
        run: |
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=dubbo-integration-consumer -jar \
          sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-consumer/target/dubbo-integration-consumer.jar > spring-and-dubbo-consumer.log 2>&1 &
      - name: start consumer service
        env:
          servicecomb.service.enableDubboRegister: true
          servicecomb.service.openMigration: true
        run: |
          nohup java -javaagent:sermant-agent-1.0.0/agent/sermant-agent.jar=appName=dubbo-integration-consumer -jar \
          sermant-integration-tests/dubbo-test/dubbo-${{ matrix.dubbo-version }}-integration-consumer/target/dubbo-integration-consumer.jar > dubbo-consumer.log 2>&1 &
      - name: waiting for consumers start
        run: |
          ps -ef | grep java
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:38022/ping 120
          bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:28820/ping 120
          ps -ef | grep java
      - name: integration test
        run: mvn -Dcontroller.port=38022 test --file sermant-integration-tests/dubbo-test/pom.xml
      - name: if failure then upload error log
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: (test-for-dubbo)-(${{ matrix.dubbo-version }}-${{ matrix.dubbo-versions }})-logs
          path: |
            ./*.log
            ./logs/**/*.log
          if-no-files-found: warn
          retention-days: 5