name: xds integration test
on:
  push:
  pull_request:
    branches:
      - '*'
    paths:
      - 'sermant-agentcore/**'
      - 'sermant-integration-tests/xds-service-test/**'
      - '.github/workflows/xds_service_test.yml'
      - '.github/actions/common/xds-service/**'
      - '.github/actions/scenarios/xds-service/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build-agent-and-cache:
    name: build agent and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: cache agent
        uses: actions/cache@v3
        with:
          path: sermant-agent-*/
          key: ${{ runner.os }}-agent-${{ github.run_id }}
      - name: cache xds service package
        uses: actions/cache@v3
        with:
          path: sermant-integration-tests/xds-service-test/product/
          key: ${{ runner.os }}-xds-service-product-${{ github.run_id }}
      - name: package agent
        run: |
          sed -i '/sermant-backend/d' pom.xml
          sed -i '/sermant-injector/d' pom.xml
          mvn package -DskipTests -Ptest --file pom.xml
          cp -r sermant-integration-tests/xds-service-test/product/spring-client/agent sermant-integration-tests/xds-service-test/product/spring-server/
  test-for-xds-service-discovery-onlysermant:
    name: Test for xds service discovery with only sermant
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: xds common operation
        uses: ./.github/actions/common/xds-service
      - name: xds service discovery
        uses: ./.github/actions/scenarios/xds-service/xds-service-discovery/sermant-only
  test-for-xds-service-discovery-with-server-envoy:
    name: Test for xds service discovery with spring-server using envoy
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: xds common operation
        uses: ./.github/actions/common/xds-service
      - name: xds service discovery
        uses: ./.github/actions/scenarios/xds-service/xds-service-discovery/server-envoy
  test-for-xds-service-discovery-with-client-envoy:
    name: Test for xds service discovery with spring-client using enovy
    runs-on: ubuntu-latest
    needs: [build-agent-and-cache]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: set java version to environment
        run: |
          echo "javaVersion=8" >> $GITHUB_ENV
      - name: xds common operation
        uses: ./.github/actions/common/xds-service
      - name: xds service discovery
        uses: ./.github/actions/scenarios/xds-service/xds-service-discovery/client-envoy